### ISSUE TITLE
Hotel ContentAPI database

### ISSUE THREAD

**Issue by Defunktt1** [hotelbeds-sdk/hotel-api-sdk-php#112]
Hello. Someone has database (or xml or something else) with all hotels and their properties? Sometimes API returns "500 server error" and my loop with requests drops.

**Comment by vmavromatis** [comment]
Hi @Defunktt1, happy New Year. Yes this is a known issue with ContentAPI that occurs specifically on INT (test) environment. Would it be possible to use an if/switch in order to retry those 500 errors until successful? Something along the lines of:

```php
	// Check HTTP status code
	if (!curl_errno($curl)) {
		switch ($http_code = curl_getinfo($curl, CURLINFO_HTTP_CODE)) {
			case 500: 
				echo 'Unexpected HTTP code: ', $http_code, "\n";
				echo $resp;
				echo "Retrying...";
				//retry call here
				break;
			default:
   				//store response here
				echo $resp;
		}
	}
```

I hope this helps, and apologies for any inconvenience.

**Comment by vmavromatis** [comment]
Hello @Defunktt1 we believe this issue has now been resolved. If you are still facing issues with 500 errors in INT, please feel free to re-open the ticket.
