### ISSUE TITLE
Internal Server Error: I I

### ISSUE THREAD

**Issue by Tahir-MatrixAMS** [hotelbeds-sdk/hotel-api-sdk-php#123]
A PHP Error was encountered
Severity: Notice

Message: Undefined index: auditData

Filename: src/HotelApiClient.php

Line Number: 178

Backtrace:

File: C:\xampp\htdocs\traveloroom.net\application\modules\Hotels\src\HotelApiClient.php
Line: 178
Function: _error_handler

File: C:\xampp\htdocs\traveloroom.net\application\modules\Hotels\src\HotelApiClient.php
Line: 150
Function: callApi

File: C:\xampp\htdocs\traveloroom.net\application\modules\Hotels\libraries\Availability.php
Line: 227
Function: __call

File: C:\xampp\htdocs\traveloroom.net\application\modules\Hotels\libraries\Availability.php
Line: 227
Function: Availability

File: C:\xampp\htdocs\traveloroom.net\application\modules\Hotels\controllers\Hotels.php
Line: 417
Function: getList

File: C:\xampp\htdocs\traveloroom.net\application\modules\Hotels\controllers\Hotels.php
Line: 547
Function: call_user_func_array

File: C:\xampp\htdocs\traveloroom.net\index.php
Line: 257
Function: require_once

**Comment by Tahir-MatrixAMS** [comment]
the about error show form last Friday please let me know

**Comment by vmavromatis** [comment]
Hello @Tahir-MatrixAMS 

This only seems to be a 'notice' level not error. It might help more if you could post your full response (it might be missing auditData?). Since the last update, you can do this with:
`echo $apiClient->getLastResponse();` (where $apiClient is defined as in the demo/example).
Then please post your full response here.

The reason you are probably getting this notice is because you are doing something like this:
```php
try {
    $availRS = $apiClient->Availability($rqData);
} catch (\hotelbeds\hotel_api_sdk\types\HotelSDKException $e) {
    $auditData = $e->getAuditData();
    error_log( $e->getMessage() );
    error_log( "Audit remote data = ".json_encode($auditData->toArray()));
    exit();
} catch (Exception $e) {
    error_log( $e->getMessage() );
    exit();
}
```
And there is no auditData returned. However this seems weird, because there should always be auditData returned (for Internal Server Errors too).

**Comment by Tahir-MatrixAMS** [comment]
Thanks bro this issue is resolved

**Comment by vmavromatis** [comment]
Good to know! Closing the issue.
