### ISSUE TITLE
Difference between API and website

### ISSUE THREAD

**Issue by Defunktt1** [hotelbeds-sdk/hotel-api-sdk-php#127]
Hello. I'm trying to get hotels in NYC from 2018-03-15 to 2018-03-18. On the website I get 434 hotels, but in the API I get only 105. I know about connectivity contracts but is this difference that big?

**Comment by vmavromatis** [comment]
Hello @Defunktt1, apologies for the delay, yes it's possible to get different results on the two platforms, due to account configuration. When you mention web I assume you refer to Hotelopia? If so, please refer to this FAQ https://developer.hotelbeds.com/docs/apitude_booking/FAQ#gen_question6

I will now be closing this ticket as it is not related to the SDK.
