### ISSUE TITLE
Call to undefined method Zend\Uri\Http::prepare()

### ISSUE THREAD

**Issue by mitko-kockovski** [hotelbeds-sdk/hotel-api-sdk-php#17]
Hi Developers,

Ive installed the app via composer and when i try to run it im getting the following error

Fatal error: Call to undefined method Zend\Uri\Http::prepare() in HotelApiClient.php on line 111.

It gives the same error when i try to test via the console 

> PHPUnit 3.7.13 by Sebastian Bergmann.
> 
> Configuration read from phpunit.xml
> 
> 
> Fatal error: Call to undefined method Zend\Uri\Http::prepare() in HotelApiClient.php on line 111

**Comment by Zavierazo** [comment]
Hi Mitko, 

You need to download all the dependences of the project. Zendramework is one of the dependences.  For it execute this command:

`composer require "hotelbeds/hotel-api-sdk-php:dev-master@dev"`

And then, try to run it again.

**Comment by mitko-kockovski** [comment]
Unfortunately the Zendframework is already installed and i cant find the function prepare in it. Thats the error im having. I think it calls in zend instead of hotel beds

**Comment by Zavierazo** [comment]
Hi Mitko, Unfortunately,I can not reproduce your problem because in my local environment everything works fine. You could send me the following information:

- Your php version. You can get it with command `php --version`
- Your vendor folder with all downloaded dependences.

Thanks you

**Comment by Zavierazo** [comment]
Hi Mitko, what url

**Comment by Zavierazo** [comment]
Hi mitko, can you check your url on HotelApiClient.ini. Url must be https to work. If you missing this please review the [step by step guide](https://github.com/hotelbeds-sdk/hotel-api-sdk-php/wiki/Step-by-step-guide-to-start-from-scratch)

**Comment by Zavierazo** [comment]
Close , if you still need help reopen please

**Comment by vessux** [comment]
For anyone having the same problem, it is caused by using api address that is http only (not https)
In hotel api client when registering alternate uri class for scheme, it is added only for https.

You will try to use http address when using test address (http://testapi.hotelbeds.com/hotel-api/1.0/hotels) As you can see, it is not available through secure https connection, its http only.

Solution is to register ApiUri for both http and https or to move testapi to https.

If you need more info about this case, feel free to hit me up with a message.

**Comment by Zavierazo** [comment]
Hi @vessux , the correct url is https://api.test.hotelbeds.com. From where you obtained the url?

**Comment by vessux** [comment]
I got it from docs at https://developer.hotelbeds.com/, it is used in explore aptitude and in test in sandbox links. I am using credentials from shop api code. Same ones are used in postman configurations. I tried using url you have provided, but when i fire up request, i only get developer inactive response. When i use url i have provided (one from the docs) its all working.

**Comment by Zavierazo** [comment]
Hi @vessux , on sandbox the url used for request is https://api.test.hotelbeds.com

![image](https://cloud.githubusercontent.com/assets/6851912/18629170/27badf14-7e64-11e6-801b-509a270b3d4d.png)

The php sdk tells you that developer inactive, because you are wrong apikeys setting in the .ini

The URL you are commenting on is the public URL of apitude explorer, which is just a website. This seems to be a bug . We will review , as only should be able to launch requests by endpoint https
